Repository JAPH254/Heaviety-Pro, pull requests merged in 2024-11, with the labels that each got.

#39 Feat/register
  frontend/pnpm-lock.yaml
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/app/store.js
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/errorBoundary.jsx
  frontend/src/pages/footer.jsx
  frontend/src/pages/home.jsx
  frontend/src/pages/landingPage.jsx
  frontend/src/pages/navbar.jsx
  frontend/src/pages/register.jsx
  frontend/src/pages/registerApi.js
Labels: Review effort [1-5]: 2

#48 Logged
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.jsx
  frontend/src/app/store.js
  frontend/src/features/register/registerApi.js
  frontend/src/pages/Error.jsx
  frontend/src/pages/Error.scss
  frontend/src/pages/Login.jsx
Labels: Review effort [1-5]: 3

#54 Feat/registering
  HeavietyPro/__pycache__/__init__.cpython-313.pyc
  HeavietyPro/__pycache__/settings.cpython-313.pyc
  HeavietyPro/__pycache__/urls.cpython-313.pyc
  HeavietyPro/__pycache__/wsgi.cpython-313.pyc
  HeavietyPro/settings.py
  authApp/__pycache__/__init__.cpython-313.pyc
  authApp/__pycache__/admin.cpython-313.pyc
  authApp/__pycache__/apps.cpython-313.pyc
  authApp/__pycache__/forms.cpython-313.pyc
  authApp/__pycache__/managers.cpython-313.pyc
  authApp/__pycache__/models.cpython-313.pyc
  authApp/migrations/__pycache__/0001_initial.cpython-313.pyc
  authApp/migrations/__pycache__/__init__.cpython-313.pyc
  db.sqlite3
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/Store.js
  frontend/src/pages/baseUrl.js
  frontend/src/pages/register.jsx
  frontend/src/pages/registerApi.js
Labels: Review effort [1-5]: 3, Possible security concern

#53 Reset password
  HeavietyPro/settings.py
  frontend/src/App.jsx
  frontend/src/app/Store.js
  frontend/src/pages/Login.jsx
  frontend/src/pages/Sidebar.jsx
  frontend/src/pages/Sidebar.scss
  frontend/src/pages/dashboard.jsx
  frontend/src/pages/dashboard.scss
  frontend/src/pages/loginSlice.js
  frontend/src/pages/register.jsx
  frontend/src/pages/registerApi.js
Labels: Review effort [1-5]: 2
